version: '3.9'

services:
  jupyter:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    container_name: jupyter
    ports:
      - '8080:8080'
    volumes:
      - .:/tf
    environment:
      JUPYTER_PORT: 8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
